
[[dependencies]]
  branch = "master"
  name = "github.com/go-gl/gl"

[[dependencies]]
  branch = "master"
  name = "github.com/go-gl/glfw"

[[dependencies]]
  branch = "master"
  name = "github.com/lukevers/glu"

[[dependencies]]
  branch = "master"
  name = "github.com/peterhellberg/wavefront"

[[dependencies]]
  branch = "master"
  name = "github.com/pkg/errors"
